/* generated by tools/gen_assets.py - do not edit */
#pragma once
#include "assets.h"
#ifdef __cplusplus
extern "C" {
#endif

extern const TfFont tf_primary;
extern const TfFont tf_primary_bold;
extern const TfFont tf_secondary;
extern const TfFont tf_big;
extern const TfFont tf_digits;
extern const TfFont tf_keyboard;

#ifdef __cplusplus
}
#endif
