/* generated by tools/gen_assets.py - do not edit */
#pragma once
#include "assets.h"
#ifdef __cplusplus
extern "C" {
#endif

extern const TfIcon tfi_subghz;
extern const TfIcon tfi_rfid125;
extern const TfIcon tfi_nfc;
extern const TfIcon tfi_infrared;
extern const TfIcon tfi_ibutton;
extern const TfIcon tfi_badusb;
extern const TfIcon tfi_gpio;
extern const TfIcon tfi_u2f;
extern const TfIcon tfi_tools;
extern const TfIcon tfi_settings;
extern const TfIcon tfi_info;
extern const TfIcon tfi_sdcard;
extern const TfIcon tfi_wifi;
extern const TfIcon tfi_bluetooth;
extern const TfIcon tfi_nrf24;
extern const TfIcon tfi_mic;
extern const TfIcon tfi_speaker;
extern const TfIcon tfi_led;
extern const TfIcon tfi_star;
extern const TfIcon tfi_folder;
extern const TfIcon tfi_filedoc;
extern const TfIcon tfi_st_battery;
extern const TfIcon tfi_st_bt;
extern const TfIcon tfi_st_sd;
extern const TfIcon tfi_st_usb;
extern const TfIcon tfi_st_clock;
extern const TfIcon tfi_st_charge;
extern const TfIcon tfi_ic_back;
extern const TfIcon tfi_ic_check;
extern const TfIcon tfi_ic_cross;
extern const TfIcon tfi_ic_quest;
extern const TfIcon tfi_ic_arrow_r;
extern const TfIcon tfi_ic_dot;
extern const TfIcon tfi_ic_lock;
extern const TfIcon tfi_ic_play;
extern const TfIcon tfi_ic_rec;
extern const TfIcon tfi_ic_save;

#define ICON_COUNT 37

#ifdef __cplusplus
}
#endif
