; FinOS — Flipper-style firmware for LilyGO T-Embed CC1101 / Plus
[platformio]
default_envs = t-embed-cc1101-plus
src_dir = src

[env]
platform = espressif32 @ 6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -D BOARD_HAS_PSRAM
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1
  -D CORE_DEBUG_LEVEL=0
  -D CONFIG_TINYUSB_HID_ENABLED=1

[env:t-embed-cc1101]
build_flags =
  ${env.build_flags}
  -D FINOS_PLUS=0

[env:t-embed-cc1101-plus]
build_flags =
  ${env.build_flags}
  -D FINOS_PLUS=1
